### ISSUE TITLE
Dropping Scarf dependency

### ISSUE THREAD

**Issue by samsch** [lotivo/sequelize-guard#10]
Heya, we have a community push to get @scarf/scarf removed from packages. It's a data protection and library expectations issue.

There's a considerable backlog of conversation on Reactiflux #news-and-links, with a reasonable starting point here: https://discordapp.com/channels/102860784329052160/105816607976095744/727600754646450206

The result being https://github.com/tannerlinsley/react-query/issues/676

**Comment by Kurzdor** [comment]
@samsch Read my issue in scarf repository, https://github.com/scarf-sh/scarf-js/issues/24

**Comment by pankajvaghela** [comment]
it will be removed in next release
