### ISSUE TITLE
Need More Examples

### ISSUE THREAD

**Issue by rakeshlanjewar** [lotivo/sequelize-guard#9]
Hello,
         I would like to use this project and contribute further as i found it interesting.
         I Request you to provide the full working example with Sequelize

**Comment by pankajvaghela** [comment]
Thanks for taking interest in this project. I am working on documentation and will have all the example soon

**Comment by tobsnti** [comment]
Hi,
I also think this is a very nice project, but I can't get it all together.
My custom UserModel is not being extended with the functions from the User API but the Database Model is correctly being migrated, so there is no more guard_users table.

My guard_migration.js:
```
var SequelizeGuard = require('sequelize-guard');
const { User } = require('../models/index');

module.exports = {
    up: (queryInterface, Sequelize) => {
        return SequelizeGuard.migration.up(queryInterface, Sequelize, { userModel: User });
    },
    down: (queryInterface, Sequelize) => {
        return SequelizeGuard.migration.down(queryInterface, Sequelize, { userModel: User });
    },
};
```

My index.js:
```
var guard = new SequelizeGuard(sequelize, User);

guard.init().allow('admin').to(['view', 'edit']).on('tab').commit();

db.sequelize = sequelize;
db.Sequelize = Sequelize;
db.guard = guard;

module.exports = db;
```

My TabController, where the Error('user.can is not a function') occurs:
```
async function getAll(req, reply) {
    const user = await User.findOne({
        where: { id: req.user.id }
    });
    if(user.can('view tab')) {
        return Tab.findAll();
    }
    reply.code(HttpStatus.UNAUTHORIZED).send({ message: 'No authorization to view tab.' })
    return;
}
```
